/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package mock.ctap

import com.fasterxml.jackson.databind.ObjectMapper
import com.webauthn4j.converter.util.CborConverter
import com.webauthn4j.converter.util.ObjectConverter
import com.webauthn4j.data.PublicKeyCredentialDescriptor
import com.webauthn4j.data.PublicKeyCredentialType
import com.webauthn4j.data.attestation.AttestationObject
import mock.ctap.interfaces.webauthnio.registration.options.WebAuthnIORegistrationOptions
import org.json.JSONObject
import spock.lang.Shared
import spock.lang.Specification

class MockAuthenticatorTest extends Specification {

    @Shared MockFido2Client fidoClient = new MockFido2Client("https://webauthn.io")

    @Shared byte[] credentialId

    def "we can register"() {
        when:
        def inputJson = "{\n" +
                "    \"rp\": {\n" +
                "        \"name\": \"webauthn.io\",\n" +
                "        \"id\": \"webauthn.io\"\n" +
                "    },\n" +
                "    \"user\": {\n" +
                "        \"id\": \"dGVzdC0y\",\n" +
                "        \"name\": \"test-2\",\n" +
                "        \"displayName\": \"test-2\"\n" +
                "    },\n" +
                "    \"challenge\": \"OvppQAinzK6Mw5WgON8wN9YZaiz9rI0Faw4Lv1ibFEzfd0AHmkv3tdr1F37I5-C66v0SkZ4YRZ1upk9-t6-wog\",\n" +
                "    \"pubKeyCredParams\": [\n" +
                "        {\n" +
                "            \"type\": \"public-key\",\n" +
                "            \"alg\": -7\n" +
                "        },\n" +
                "        {\n" +
                "            \"type\": \"public-key\",\n" +
                "            \"alg\": -257\n" +
                "        }\n" +
                "    ],\n" +
                "    \"timeout\": 60000,\n" +
                "    \"excludeCredentials\": [],\n" +
                "    \"authenticatorSelection\": {\n" +
                "        \"residentKey\": \"preferred\",\n" +
                "        \"requireResidentKey\": false,\n" +
                "        \"userVerification\": \"preferred\"\n" +
                "    },\n" +
                "    \"attestation\": \"none\",\n" +
                "    \"extensions\": {\n" +
                "        \"credProps\": true\n" +
                "    }\n" +
                "}"
        String out = fidoClient.register(inputJson)

        then:
        System.out.println(out)

    }

    def "we can login"() {
        when:
        String inputJson = ""
        def username = "vilson"
        def output = fidoClient.login(inputJson, username)

        then:
        System.out.println(output);
    }

    String webAuthnIOOutput(WebAuthnIORegistrationOptions request, AttestationObject object) {

        def clientDataJson = new JSONObject()
                                .put("type", "webauthn.create")
                                .put("challenge", request.getChallenge())
                                .put("origin", "https://webauthn.io")
                                .put("crossOrigin", false)
                                .toString().getBytes()
        def encodedClientDataJson = Base64.getEncoder().withoutPadding().encodeToString(clientDataJson)
        String id = Base64.getEncoder().withoutPadding().encodeToString(object.getAuthenticatorData().getAttestedCredentialData().getCredentialId())
        CborConverter converter = new ObjectConverter().getCborConverter()
        def attestationObject = Base64.getEncoder().withoutPadding().encodeToString(converter.writeValueAsBytes(object))
        return new JSONObject()
            .put("username", request.getUser().getName())
            .put("response", new JSONObject()
                .put("id", id)
                .put("rawId", id)
                .put("response", new JSONObject()
                    .put("attestationObject", attestationObject)
                    .put("clientDataJSON", encodedClientDataJson)
                    .put("transports", ["nfc", "usb"])
                )
                .put("type", "public-key")
                .put("clientExtensionResults", new JSONObject()
                    .put("credProps", new JSONObject()
                        .put("rk", true)
                    )
                )
                .put("authenticatorAttachment", "cross-platform")
            ).toString()
    }
}
